---
name: EarlyRetired
description: Early Retired Me is my journey to achieve FIRE.
logo: assets/images/logo.png
favicon: assets/images/favicon.ico
email: nitigyasharma@hotmail.com
mailchimp-list: "https://gmail.us2.list-manage.com/subscribe/post?u=4078ace2f9a15e91cd2c77df5&amp;id=13cb0014a4"
include:
- _pages
permalink: "/:title/"
plugins:
- jekyll-menus
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
authors:
  nitigya:
    name: Nitigya
    site: https://www.wowthemes.net
    avatar: "/assets/images/avatar_nitigya.png"
    bio: Hi, I am Nitigya Sharma, I am the author of the blog you are reading.
    email: nitigyasharma@hotmail.com
    # twitter: https://twitter.com/wowthemesnet
  nikki:
    name: Nikki
    site: https://www.wowthemes.net
    avatar: "/assets/images/avatar2.jpg"
    bio: Blogger, and Nonu.
    email: kumarinikki99@gmail.com
    twitter: https://twitter.com/wowthemesnet
defaults:
- scope:
    path: _posts
  values:
    layout: post
    author: nitigya
    avatar: "/assets/images/avatar_nitigya.png"
- scope:
    path: _pages
  values:
    layout: page
paginate: "10"
